"""Base types and utilities for agent implementations."""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Optional


@dataclass
class AgentContext:
    """Contextual input provided to each agent invocation."""

    task_id: str
    goal: str
    payload: dict[str, Any] = field(default_factory=dict)
    prior_outputs: dict[str, Any] = field(default_factory=dict)


@dataclass
class AgentArtifact:
    """Artifacts generated by agents (e.g., files, diagrams)."""

    uri: Optional[str]
    description: str
    media_type: str = "text/plain"


@dataclass
class AgentResponse:
    """Structured agent execution result."""

    success: bool
    output: dict[str, Any] = field(default_factory=dict)
    message: str = ""
    artifacts: list[AgentArtifact] = field(default_factory=list)


class AgentError(RuntimeError):
    """Raised when an agent cannot fulfill its task."""


class Agent(ABC):
    """Abstract base class for all agents."""

    def __init__(self, name: str) -> None:
        self.name = name
        self.logger = logging.getLogger(f"agents.{self.name.lower()}")

    @abstractmethod
    def execute(self, context: AgentContext) -> AgentResponse:
        """Run the agent for the provided context."""
